// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAAtZectgGx-JepFZp5by3gkN8b0HB1js',
    appId: '1:481647971051:web:f4339e1e0c4dd07fc80cae',
    messagingSenderId: '481647971051',
    projectId: 'weath-app',
    authDomain: 'weath-app.firebaseapp.com',
    storageBucket: 'weath-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-8KGfurU8ism1xIJ5Wh_ju8zKqa7Gp3I',
    appId: '1:481647971051:android:1c5dadb2f2a06606c80cae',
    messagingSenderId: '481647971051',
    projectId: 'weath-app',
    storageBucket: 'weath-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK1lIebpE8kTdjiNsWMAxL1J7QdhB_Ogo',
    appId: '1:481647971051:ios:b63aafed53457f3dc80cae',
    messagingSenderId: '481647971051',
    projectId: 'weath-app',
    storageBucket: 'weath-app.appspot.com',
    iosBundleId: 'com.abalcan.wapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK1lIebpE8kTdjiNsWMAxL1J7QdhB_Ogo',
    appId: '1:481647971051:ios:b63aafed53457f3dc80cae',
    messagingSenderId: '481647971051',
    projectId: 'weath-app',
    storageBucket: 'weath-app.appspot.com',
    iosBundleId: 'com.abalcan.wapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAAtZectgGx-JepFZp5by3gkN8b0HB1js',
    appId: '1:481647971051:web:64250ff7c8e49933c80cae',
    messagingSenderId: '481647971051',
    projectId: 'weath-app',
    authDomain: 'weath-app.firebaseapp.com',
    storageBucket: 'weath-app.appspot.com',
  );
}
